### ISSUE TITLE
Can't get to forecast page

### ISSUE THREAD

**Issue by johnrobertlawson** [Bingham-Research-Center/ozone-brc-website#7]
Looks like there's a bug as I can't click to get to the forecast page that the icon represents. Also, I can't click to the "blogs" (I better call them written outlook forecasts, it isn't fan-fic). Is there a broken link somewhere in the code?

**Comment by ElspethMontague** [comment]
I also noticed that, I think its because I transferred all the info to a new page, fixing that today.

**Comment by ElspethMontague** [comment]
This should be working now
